[build]
  publish = "."

# Form handling
[forms]
  # Define the main subscription form
  [forms.subscription]
    name = "subscription"
    success_url = "/success.html"
    
# Define redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Specify the form settings
[[forms.subscription.fields]]
  name = "name"
  required = true

[[forms.subscription.fields]]
  name = "email"
  required = true

[[forms.subscription.fields]]
  name = "userType"
  required = true

[[forms.subscription.fields]]
  name = "preferences"
  required = false

# Headers to improve security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
